### ISSUE TITLE
workingDirectory config option does not have any effect

### ISSUE THREAD

**Issue by qlonik** [develar/ij-rc-producer#4]
Hey, I found that regardless of what value I put into `workingDirectory` field, it is not added into the 'workingDirectory' field in IntelliJ IDEA run dialog. Could you clarify if I'm doing something wrong or is it a bug?

In order to make it work, I had to add node argument changing the directory before running whatever I need to be run.

```yaml
- &defaults
#  workingDirectory: "${PROJECT_DIR}/my_project"
#  workingDirectory: "./my_project"
  files: ["**/__tests__/**/*", "**/*.spec.*", "**/*.test.*", "!**/node_modules/**/*"]
  beforeRun: typescript
  nodeArgs: ["-e", "process.chdir('./my_project'); process.argv[1]=process.argv[1].slice(process.argv[1].indexOf('./node_modules')); require('module').runMain()"]
  script: "my_project/./node_modules/.bin/ava"
  scriptArgs: ["src/**/${fileNameWithoutExt}.*"]
  rcName: "${fileNameWithoutExt}"

-
  <<: *defaults
  lineRegExp: '^\s*test(?:\.[^(]+)*\((?:\s|\n)*(?:"|'')([^"'']+)'
  scriptArgs: ["-m", "${0}", "src/**/${fileNameWithoutExt}.*"]
  rcName: "${fileNameWithoutExt}.${0}"
```
